### ISSUE TITLE
cf-cli fails with serial ports after COM9: under Windows

### ISSUE THREAD

**Issue by ethomas997** [stronnag/mwptools#4]
When running cf-cli on a Windows 7 laptop with a serial port is after COM9: (for example, COM15:), the program fails with a message like "07:09:16 open COM15: - The filename, directory name, or volume label syntax is incorrect. (0x7b)".  The CleanFlight configuration is able to successfully reach the flight controller using the same serial port.  If the serial port is renamed to a "lower" port number (for example, COM7:), then cf-cli is able to run successfully.

--ET

**Comment by stronnag** [comment]
I think this is because Win7 no longer uses the NT naming space (and you could probably only have 1-9 there)?. Anyway, I have no means to fix this (access to the OS, Microsoft tools), so it will have to be documented as a restriction. (e.g. the COM device section of  https://msdn.microsoft.com/en-gb/library/windows/desktop/aa365247(v=vs.85).aspx)
